//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mictlanix.Iam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mictlanix.Iam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Usuario.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Convenios.
        /// </summary>
        public static string AllowCreateArrangements {
            get {
                return ResourceManager.GetString("AllowCreateArrangements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Contrapartes.
        /// </summary>
        public static string AllowCreateOrganizations {
            get {
                return ResourceManager.GetString("AllowCreateOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Revisiones de Convenios.
        /// </summary>
        public static string AllowCreateRequests {
            get {
                return ResourceManager.GetString("AllowCreateRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Dependencias.
        /// </summary>
        public static string AllowCreateSchools {
            get {
                return ResourceManager.GetString("AllowCreateSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Convenios.
        /// </summary>
        public static string AllowDeleteArrangements {
            get {
                return ResourceManager.GetString("AllowDeleteArrangements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Contrapartes.
        /// </summary>
        public static string AllowDeleteOrganizations {
            get {
                return ResourceManager.GetString("AllowDeleteOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Revisiones de Convenios.
        /// </summary>
        public static string AllowDeleteRequests {
            get {
                return ResourceManager.GetString("AllowDeleteRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Dependencias.
        /// </summary>
        public static string AllowDeleteSchools {
            get {
                return ResourceManager.GetString("AllowDeleteSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Convenios.
        /// </summary>
        public static string AllowEditArrangements {
            get {
                return ResourceManager.GetString("AllowEditArrangements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Contrapartes.
        /// </summary>
        public static string AllowEditOrganizations {
            get {
                return ResourceManager.GetString("AllowEditOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Revisiones de Convenios.
        /// </summary>
        public static string AllowEditRequests {
            get {
                return ResourceManager.GetString("AllowEditRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Dependencias.
        /// </summary>
        public static string AllowEditSchools {
            get {
                return ResourceManager.GetString("AllowEditSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Convenios.
        /// </summary>
        public static string AllowReadArrangements {
            get {
                return ResourceManager.GetString("AllowReadArrangements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Contrapartes.
        /// </summary>
        public static string AllowReadOrganizations {
            get {
                return ResourceManager.GetString("AllowReadOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Revisiones de Convenios.
        /// </summary>
        public static string AllowReadRequests {
            get {
                return ResourceManager.GetString("AllowReadRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Dependencias.
        /// </summary>
        public static string AllowReadSchools {
            get {
                return ResourceManager.GetString("AllowReadSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPN.
        /// </summary>
        public static string Alt_Logo {
            get {
                return ResourceManager.GetString("Alt_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexos.
        /// </summary>
        public static string Annexes {
            get {
                return ResourceManager.GetString("Annexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio.
        /// </summary>
        public static string Arrangement {
            get {
                return ResourceManager.GetString("Arrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisión.
        /// </summary>
        public static string ArrangementRequests {
            get {
                return ResourceManager.GetString("ArrangementRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenios.
        /// </summary>
        public static string Arrangements {
            get {
                return ResourceManager.GetString("Arrangements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encargado.
        /// </summary>
        public static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autores.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar a la Lista.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegación o Municipio.
        /// </summary>
        public static string Borough {
            get {
                return ResourceManager.GetString("Borough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Convenio.
        /// </summary>
        public static string CreateArragement {
            get {
                return ResourceManager.GetString("CreateArragement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Nuevo.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisó.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Actual.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y Hora.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de SiSeCoVi (Mictlanix Iam).
        /// </summary>
        public static string DisplayName_About {
            get {
                return ResourceManager.GetString("DisplayName_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiSeCoVi - IPN Secretaría de Extensión e Integración Social.
        /// </summary>
        public static string DisplayName_Application {
            get {
                return ResourceManager.GetString("DisplayName_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Convenios.
        /// </summary>
        public static string DisplayName_Arrangement {
            get {
                return ResourceManager.GetString("DisplayName_Arrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Revisiones.
        /// </summary>
        public static string DisplayName_ArrangementRequests {
            get {
                return ResourceManager.GetString("DisplayName_ArrangementRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de Contraseña.
        /// </summary>
        public static string DisplayName_ChangePassword {
            get {
                return ResourceManager.GetString("DisplayName_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Sesión.
        /// </summary>
        public static string DisplayName_LogOn {
            get {
                return ResourceManager.GetString("DisplayName_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Contrapartes.
        /// </summary>
        public static string DisplayName_Organization {
            get {
                return ResourceManager.GetString("DisplayName_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Usuario.
        /// </summary>
        public static string DisplayName_Register {
            get {
                return ResourceManager.GetString("DisplayName_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Dependencias Politécnicas.
        /// </summary>
        public static string DisplayName_School {
            get {
                return ResourceManager.GetString("DisplayName_School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Usuarios.
        /// </summary>
        public static string DisplayName_Users {
            get {
                return ResourceManager.GetString("DisplayName_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio Electrónico.
        /// </summary>
        public static string ElectronicMedia {
            get {
                return ResourceManager.GetString("ElectronicMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final de la Vigencia.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Exterior.
        /// </summary>
        public static string ExteriorNumber {
            get {
                return ResourceManager.GetString("ExteriorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        public static string Folio {
            get {
                return ResourceManager.GetString("Folio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimiento.
        /// </summary>
        public static string FollowUp {
            get {
                return ResourceManager.GetString("FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato PV1, Pv2 y PV3.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Interior.
        /// </summary>
        public static string InteriorNumber {
            get {
                return ResourceManager.GetString("InteriorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string IsAdministrator {
            get {
                return ResourceManager.GetString("IsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentación Legal (Contraparte).
        /// </summary>
        public static string LegalDocuments {
            get {
                return ResourceManager.GetString("LegalDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figura Jurídica.
        /// </summary>
        public static string LegalRequirement {
            get {
                return ResourceManager.GetString("LegalRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cambio de contraseña no fue exitoso. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string Message_ChangePasswordFail {
            get {
                return ResourceManager.GetString("Message_ChangePasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contraseña se ha cambiado exitosamente..
        /// </summary>
        public static string Message_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Message_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es incorrecta o la contraseña nueva es inválida..
        /// </summary>
        public static string Message_ChangePasswordWrong {
            get {
                return ResourceManager.GetString("Message_ChangePasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de borrar esto?.
        /// </summary>
        public static string Message_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Message_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string Message_InvalidUserPassword {
            get {
                return ResourceManager.GetString("Message_InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese su usuario y contraseña. O si usted no tiene un usuario, favor de.
        /// </summary>
        public static string Message_LoginRegister {
            get {
                return ResourceManager.GetString("Message_LoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El inicio de sesión no fue exitoso. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string Message_LoginUnsuccessful {
            get {
                return ResourceManager.GetString("Message_LoginUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no fue exitoso. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string Message_RegisterUnsuccessful {
            get {
                return ResourceManager.GetString("Message_RegisterUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido. Por favor, verifica tus datos y vuelve a intentarlo. Si el problema persiste contacte a su administrador de sistema..
        /// </summary>
        public static string Message_UnknownError {
            get {
                return ResourceManager.GetString("Message_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario ya existe..
        /// </summary>
        public static string Message_UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("Message_UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonia.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Nueva.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto del Convenio.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraparte.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrapartes.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensión Telefónica.
        /// </summary>
        public static string PhoneExt {
            get {
                return ResourceManager.GetString("PhoneExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Entrada.
        /// </summary>
        public static string ReceiptDate {
            get {
                return ResourceManager.GetString("ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Recordarme?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficio de Solicitud.
        /// </summary>
        public static string RequestForm {
            get {
                return ResourceManager.GetString("RequestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisiones.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable Técnico.
        /// </summary>
        public static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escrito del Responsable Técnico.
        /// </summary>
        public static string ResponsibleStatement {
            get {
                return ResourceManager.GetString("ResponsibleStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencia Politécnica.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorización Académica.
        /// </summary>
        public static string SchoolAutorization {
            get {
                return ResourceManager.GetString("SchoolAutorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencias.
        /// </summary>
        public static string Schools {
            get {
                return ResourceManager.GetString("Schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        public static string SchoolType {
            get {
                return ResourceManager.GetString("SchoolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        public static string SchoolType_College {
            get {
                return ResourceManager.GetString("SchoolType_College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Superior.
        /// </summary>
        public static string SchoolType_HighSchool {
            get {
                return ResourceManager.GetString("SchoolType_HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NP.
        /// </summary>
        public static string SchoolType_None {
            get {
                return ResourceManager.GetString("SchoolType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posgrado.
        /// </summary>
        public static string SchoolType_University {
            get {
                return ResourceManager.GetString("SchoolType_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Expedientes.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión de Aprobación.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso a Subcomite.
        /// </summary>
        public static string SessionDate {
            get {
                return ResourceManager.GetString("SessionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abreviatura.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Firma.
        /// </summary>
        public static string SignatureDate {
            get {
                return ResourceManager.GetString("SignatureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisión UDV.
        /// </summary>
        public static string Status01 {
            get {
                return ResourceManager.GetString("Status01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisión Abogados Delegados UPDCE.
        /// </summary>
        public static string Status02 {
            get {
                return ResourceManager.GetString("Status02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenios Rechazados en Sesiones del Subcomité.
        /// </summary>
        public static string Status03 {
            get {
                return ResourceManager.GetString("Status03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma del Director de la UPDCE.
        /// </summary>
        public static string Status04 {
            get {
                return ResourceManager.GetString("Status04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma del Secretario de Extensión e Integración Social.
        /// </summary>
        public static string Status05 {
            get {
                return ResourceManager.GetString("Status05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remitido a la Dirección de Normatividad, Consulta y Dictaminación.
        /// </summary>
        public static string Status06 {
            get {
                return ResourceManager.GetString("Status06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma del Director de la UPDCE.
        /// </summary>
        public static string Status07 {
            get {
                return ResourceManager.GetString("Status07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma de la Contraparte.
        /// </summary>
        public static string Status08 {
            get {
                return ResourceManager.GetString("Status08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio que Paso a Subcomité.
        /// </summary>
        public static string Status09 {
            get {
                return ResourceManager.GetString("Status09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio Aprobado por el Subcomité (concluido).
        /// </summary>
        public static string Status10 {
            get {
                return ResourceManager.GetString("Status10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio con Firmas Autógrafas Falta Formato PV3.
        /// </summary>
        public static string Status11 {
            get {
                return ResourceManager.GetString("Status11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio Revisado, Falta Documentación.
        /// </summary>
        public static string Status12 {
            get {
                return ResourceManager.GetString("Status12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio con Observacione Jurídicas y Comentarios para revisión de las partes.
        /// </summary>
        public static string Status13 {
            get {
                return ResourceManager.GetString("Status13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio Rechazado Nuevos Lineamientos y/o Extemporalidad de fecha de firma.
        /// </summary>
        public static string Status14 {
            get {
                return ResourceManager.GetString("Status14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio Detenido.
        /// </summary>
        public static string Status15 {
            get {
                return ResourceManager.GetString("Status15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio Cancelado.
        /// </summary>
        public static string Status16 {
            get {
                return ResourceManager.GetString("Status16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de Seguimiento de Convenios Vinculados.
        /// </summary>
        public static string Title_Application {
            get {
                return ResourceManager.GetString("Title_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revsión de Arreglo.
        /// </summary>
        public static string Title_ArragementRequest {
            get {
                return ResourceManager.GetString("Title_ArragementRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisiones.
        /// </summary>
        public static string Title_ArrangementRequests {
            get {
                return ResourceManager.GetString("Title_ArrangementRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenios.
        /// </summary>
        public static string Title_Arrangements {
            get {
                return ResourceManager.GetString("Title_Arrangements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Title_ChangePassword {
            get {
                return ResourceManager.GetString("Title_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituto Politécnico Nacional.
        /// </summary>
        public static string Title_Logo {
            get {
                return ResourceManager.GetString("Title_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Sesión.
        /// </summary>
        public static string Title_LogOn {
            get {
                return ResourceManager.GetString("Title_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrapartes.
        /// </summary>
        public static string Title_Organizations {
            get {
                return ResourceManager.GetString("Title_Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string Title_Register {
            get {
                return ResourceManager.GetString("Title_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependecias.
        /// </summary>
        public static string Title_Schools {
            get {
                return ResourceManager.GetString("Title_Schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Title_Users {
            get {
                return ResourceManager.GetString("Title_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Instrumento Jurídico.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        public static string TypeSchool {
            get {
                return ResourceManager.GetString("TypeSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} debe ser posterior a {1}..
        /// </summary>
        public static string Validation_DateGreaterThan {
            get {
                return ResourceManager.GetString("Validation_DateGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo introducido no corresponde a un {0}..
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario y/o contraseña son invalidos..
        /// </summary>
        public static string Validation_InvalidLogOn {
            get {
                return ResourceManager.GetString("Validation_InvalidLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es inválida..
        /// </summary>
        public static string Validation_InvalidPassword {
            get {
                return ResourceManager.GetString("Validation_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nueva contraseña y la confirmación no coinciden..
        /// </summary>
        public static string Validation_PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("Validation_PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es obligatorio..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} debe tener al menos {2} caracteres de largo..
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo introducido no corresponde a un {0}..
        /// </summary>
        public static string Validation_Url {
            get {
                return ResourceManager.GetString("Validation_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se especificó un elemento válido para {0}..
        /// </summary>
        public static string Validation_WrongId {
            get {
                return ResourceManager.GetString("Validation_WrongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de la Vigencia.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitio Web.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
